// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3_J15iyYJ_d5g4IM9rUvYvemuBW8KCUs',
    appId: '1:374511035302:ios:73b80d374d6176f86ca567',
    messagingSenderId: '374511035302',
    projectId: 'daylog-16724',
    storageBucket: 'daylog-16724.firebasestorage.app',
    iosBundleId: 'com.example.daylog',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd-uOdFJAMJpfIgcL-aLlRNVcxhe5OTdc',
    appId: '1:374511035302:web:0678d52f9f717bce6ca567',
    messagingSenderId: '374511035302',
    projectId: 'daylog-16724',
    authDomain: 'daylog-16724.firebaseapp.com',
    storageBucket: 'daylog-16724.firebasestorage.app',
    measurementId: 'G-8L6G0MY4EB',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3_J15iyYJ_d5g4IM9rUvYvemuBW8KCUs',
    appId: '1:374511035302:ios:73b80d374d6176f86ca567',
    messagingSenderId: '374511035302',
    projectId: 'daylog-16724',
    storageBucket: 'daylog-16724.firebasestorage.app',
    iosBundleId: 'com.example.daylog',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZvHh288fjt_kguOzpLoE4jJSVFgvMIMI',
    appId: '1:374511035302:android:3470eff0797b51ce6ca567',
    messagingSenderId: '374511035302',
    projectId: 'daylog-16724',
    storageBucket: 'daylog-16724.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBd-uOdFJAMJpfIgcL-aLlRNVcxhe5OTdc',
    appId: '1:374511035302:web:4eedbd1bdb6e2d5f6ca567',
    messagingSenderId: '374511035302',
    projectId: 'daylog-16724',
    authDomain: 'daylog-16724.firebaseapp.com',
    storageBucket: 'daylog-16724.firebasestorage.app',
    measurementId: 'G-TMQBLWG3E3',
  );

}